name: Build Placcon Apps

on: [push]

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Teljes repository checkout (tagekkel)
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Python beállítása
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        architecture: x86

    - name: Függőségek telepítése (PyInstaller és requirements)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: placcon_display.exe buildelése (kiosk, placcon1)
      run: |
        pyinstaller --onefile --windowed --icon="placcon.ico" --name "placcon_display" launch_placcon.py -- --profile placcon1 --kiosk

    - name: placcon.exe buildelése (fullscreen app, placconapp)
      run: |
        pyinstaller --onefile --windowed --icon="placcon.ico" --name "placcon" launch_placcon.py -- --profile placconapp

    - name: Buildelt Exék feltöltése artifactként
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Placcon-Executables
        path: |
          dist/placcon_display.exe
          dist/placcon.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Teljes repository checkout (tagekkel)
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Python beállítása
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Függőségek telepítése (PyInstaller és requirements)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: placcon_display.app buildelése (kiosk, placcon1)
      run: |
        pyinstaller --windowed --icon="placcon.icns" --name "placcon_display" launch_placcon.py -- --profile placcon1 --kiosk

    - name: placcon.app buildelése (fullscreen app, placconapp)
      run: |
        pyinstaller --windowed --icon="placcon.icns" --name "placcon" launch_placcon.py -- --profile placconapp

    - name: Buildelt Appok feltöltése artifactként
      uses: actions/upload-artifact@v4
      with:
        name: MacOS-Placcon-Apps
        path: |
          dist/placcon_display.app
          dist/placcon.app

  release:
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
    - name: Legutóbbi tag lekérdezése és új verzió generálása
      id: get_version
      run: |
        # Összes v1.*.0 tag kilistázása, csak a minor számot nézzük
        tags=$(git tag -l 'v1.*.0')
        max_minor=0
        for tag in $tags; do
          minor=$(echo $tag | sed -E 's/v1\.([0-9]+)\.0/\1/')
          if [[ $minor =~ ^[0-9]+$ ]] && (( minor > max_minor )); then
            max_minor=$minor
          fi
        done
        next_minor=$((max_minor+1))
        new_tag="v1.$next_minor.0"
        echo "Következő verzió: $new_tag"
        echo "tag=$new_tag" >> $GITHUB_OUTPUT

    - name: Windows artifact letöltése
      uses: actions/download-artifact@v4
      with:
        name: Windows-Placcon-Executables
        path: artifacts/windows

    - name: MacOS artifact letöltése
      uses: actions/download-artifact@v4
      with:
        name: MacOS-Placcon-Apps
        path: artifacts/macos

    - name: GitHub Release létrehozása és fájlok feltöltése
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.get_version.outputs.tag }}
        name: ${{ steps.get_version.outputs.tag }}
        files: |
          artifacts/windows/placcon_display.exe
          artifacts/windows/placcon.exe
          artifacts/macos/placcon_display.app
          artifacts/macos/placcon.app
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 