name: Build Placcon Apps

on: [push]

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Kód letöltése
      uses: actions/checkout@v4

    - name: Python beállítása
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        architecture: x86

    - name: Függőségek telepítése (PyInstaller és requirements)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: placcon_display.exe buildelése (kiosk, placcon1)
      run: |
        pyinstaller --onefile --windowed --icon="placcon.ico" --name "placcon_display" launch_placcon.py -- --profile placcon1 --kiosk

    - name: placcon.exe buildelése (fullscreen app, placconapp)
      run: |
        pyinstaller --onefile --windowed --icon="placcon.ico" --name "placcon" launch_placcon.py -- --profile placconapp

    - name: Buildelt Exék feltöltése artifactként
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Placcon-Executables
        path: |
          dist/placcon_display.exe
          dist/placcon.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Kód letöltése
      uses: actions/checkout@v4

    - name: Python beállítása
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Függőségek telepítése (PyInstaller és requirements)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: placcon_display.app buildelése (kiosk, placcon1)
      run: |
        pyinstaller --windowed --icon="placcon.icns" --name "placcon_display" launch_placcon.py -- --profile placcon1 --kiosk

    - name: placcon.app buildelése (fullscreen app, placconapp)
      run: |
        pyinstaller --windowed --icon="placcon.icns" --name "placcon" launch_placcon.py -- --profile placconapp

    - name: Buildelt Appok feltöltése artifactként
      uses: actions/upload-artifact@v4
      with:
        name: MacOS-Placcon-Apps
        path: |
          dist/placcon_display.app
          dist/placcon.app

  release:
    needs: build-windows
    runs-on: ubuntu-latest
    steps:
    - name: Artifactok letöltése
      uses: actions/download-artifact@v4
      with:
        name: Windows-Placcon-Executables
        path: artifacts/windows

    - name: GitHub Release létrehozása és fájlok feltöltése
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.0
        name: 1.0.0
        files: |
          artifacts/windows/placcon_display.exe
          artifacts/windows/placcon.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 