name: Build Linux

on:
  push:
    branches: [ electron-v2 ]
  pull_request:
    branches: [ electron-v2 ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build for Linux
      run: npm run build:linux
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Clean dist folder (keep only DEB files)
      run: |
        find ./dist -type f ! -name '*.deb' -delete
        find ./dist -type d -empty -delete

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: placcon-launcher-linux
        path: dist/
        retention-days: 0

    - name: List artifacts
      run: |
        echo "Built artifacts for Linux:"
        ls -la dist/ 