name: Build Electron App Test for Windows x86 & ARM64

on: [push]

permissions:
  contents: write

jobs:
  build-windows-x86:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Build Windows x86 app test
      shell: pwsh
      run: |
        if (Test-Path src/assets/favicon-test.ico) { Copy-Item src/assets/favicon-test.ico src/assets/favicon.ico -Force }
        if (Test-Path src/assets/favicon-test.icns) { Copy-Item src/assets/favicon-test.icns src/assets/favicon.icns -Force }
        if (Test-Path src/assets/favicon-test.png) { Copy-Item src/assets/favicon-test.png src/assets/favicon.png -Force }
        $env:PLACCON_MODE="app"
        $env:PLACCON_ENV="test"
        npx electron-builder --config electron-builder.app.json --win --ia32 --publish never
        git checkout -- src/assets/favicon.ico src/assets/favicon.icns src/assets/favicon.png

    - name: Upload Windows x86 app test artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-x86-app-test
        path: dist/*.exe
        retention-days: 30

  build-windows-arm64:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Build Windows ARM64 app test
      shell: pwsh
      run: |
        $env:PLACCON_MODE="app"
        $env:PLACCON_ENV="test"
        npx electron-builder --config electron-builder.app.json --win --arm64 --publish never

    - name: Upload Windows ARM64 app test artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-arm64-app-test
        path: dist/*.exe
        retention-days: 30 