name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-all:
    strategy:
      matrix:
        platform: [mac, win, linux]
        include:
          - platform: mac
            runner: macos-latest
            extension: dmg
          - platform: win
            runner: windows-latest
            extension: exe
          - platform: linux
            runner: ubuntu-latest
            extension: deb
    
    runs-on: ${{ matrix.runner }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build for ${{ matrix.platform }}
      run: npm run build:${{ matrix.platform }}

    - name: List build outputs
      run: |
        echo "Build outputs for ${{ matrix.platform }}:"
        find ./dist -type f | sort

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: placcon-launcher-${{ matrix.platform }}
        path: dist/
        retention-days: 0

  create-release:
    needs: build-all
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Find and list release files
      id: find_files
      run: |
        echo "Artifacts directory structure:"
        find artifacts -type f | sort
        echo ""
        echo "Looking for release files:"
        
        # Find DMG files
        DMG_FILES=$(find artifacts -name "*.dmg" -type f)
        echo "DMG files found: $DMG_FILES"
        
        # Find EXE files  
        EXE_FILES=$(find artifacts -name "*.exe" -type f)
        echo "EXE files found: $EXE_FILES"
        
        # Find DEB files
        DEB_FILES=$(find artifacts -name "*.deb" -type f)
        echo "DEB files found: $DEB_FILES"
        
        # Create file list for release
        RELEASE_FILES=""
        if [ ! -z "$DMG_FILES" ]; then
          RELEASE_FILES="$RELEASE_FILES $DMG_FILES"
        fi
        if [ ! -z "$EXE_FILES" ]; then
          RELEASE_FILES="$RELEASE_FILES $EXE_FILES"
        fi
        if [ ! -z "$DEB_FILES" ]; then
          RELEASE_FILES="$RELEASE_FILES $DEB_FILES"
        fi
        
        echo "Release files: $RELEASE_FILES"
        echo "files=$RELEASE_FILES" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ steps.find_files.outputs.files }}
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 