name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-all:
    strategy:
      matrix:
        platform: [mac, win, linux]
        include:
          - platform: mac
            runner: macos-latest
            extension: dmg
          - platform: win
            runner: windows-latest
            extension: exe
          - platform: linux
            runner: ubuntu-latest
            extension: deb
    
    runs-on: ${{ matrix.runner }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build for ${{ matrix.platform }}
      run: npm run build:${{ matrix.platform }}
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Clean and prepare artifacts
      run: |
        if [ "$RUNNER_OS" = "Windows" ]; then
          Get-ChildItem -Path ./dist -Recurse -File | Where-Object { $_.Extension -ne '.${{ matrix.extension }}' } | Remove-Item -Force
        else
          find ./dist -type f ! -name '*.${{ matrix.extension }}' -delete
          find ./dist -type d -empty -delete
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: placcon-launcher-${{ matrix.platform }}
        path: dist/
        retention-days: 0

  create-release:
    needs: build-all
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/placcon-launcher-mac/dist/*.dmg
          artifacts/placcon-launcher-win/dist/*.exe
          artifacts/placcon-launcher-linux/dist/*.deb
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 