name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            platform: mac
            artifact-pattern: "*.dmg"
          - os: ubuntu-latest
            platform: linux
            artifact-pattern: "*.deb"
          - os: windows-latest
            platform: win
            artifact-pattern: "*.exe"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build for ${{ matrix.platform }}
      run: npm run build:${{ matrix.platform }}
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Clean dist folder (keep only installers)
      run: |
        find ./dist -type f ! \( -name '${{ matrix.artifact-pattern }}' \) -delete
        find ./dist -type d -empty -delete

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: placcon-launcher-${{ matrix.platform }}
        path: dist/
        retention-days: 0

  create-release:
    needs: build-and-release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/placcon-launcher-mac/dist/*.dmg
          artifacts/placcon-launcher-linux/dist/*.deb
          artifacts/placcon-launcher-win/dist/*.exe
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 